---
title: "@kylewalker.bsky.social's Map"
subtitle: ""
excerpt: ""
date: 2024-11-16
author: "Steve Ewing"
draft: false
series:
tags: ["R", "bluesky"]
categories:
layout: single
---

Can I copy Kyle's map and post to bsky as a reply?

First the map.
```{r}
library(tidycensus)
library(tigris)
library(tidyverse)
options(tigris_use_cache = TRUE)

# Grab the data
us_wfh <- get_acs(
  geography = "puma",
  variables = "DP03_0024P",
  year = 2023,
  survey = "acs1",
  geometry = TRUE
) 

# Interactive map with mapgl
library(mapgl)

# Format the popup
popup_content <- glue::glue(
  "<strong>{us_wfh$NAME}</strong><br>",
  "% working from home: {us_wfh$estimate}"
)

us_wfh$popup <- popup_content

# Build the interactive map
wfh_map <- mapboxgl(
  style = mapbox_style("light"), 
  center = c(-98.5795, 39.8283), 
  zoom = 3
) %>%
  add_fill_layer(
    id = "puma_wfh",
    source = us_wfh,
    fill_color = interpolate(
      column = "estimate",
      values = c(1.4, 9.4, 14.9, 22.2, 36.5),
      stops = viridisLite::plasma(5),
      na_color = "lightgrey"
    ),
    fill_opacity = 0.7,
    popup = "popup", 
    hover_options = list(
      fill_color = "cyan",
      fill_opacity = 1
    )
  ) %>%
  add_legend(
    "% working from home by PUMA, 2023 1-year ACS",
    values = c("1.4%", "9.4%", "14.9%", "22.2%", "36.5%"),
    colors = viridisLite::plasma(5)
  )

wfh_map
```

Map works, can confirm. Now to save it then try to post it as a reply

```{r}
# Save the map
# saveWidget(wfh_map, "C:/Users/steph/OneDrive/warp_and_weft_data/content/blog/k_walker_map/map.html", selfcontained = TRUE)
```

Get Kyle's Posts

```{r, comments = FALSE}
library(bskyr)

kw_posts <- bs_get_author_feed("kylewalker.bsky.social", limit = 10)

# Get the latest post
latest_post <- kw_posts[1,]

# Post the map as a reply
bs_post(
  text = "Nice map, code works, thanks for sharing!",
  reply = latest_post$reply_root.uri[1]
)
```

